/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as AdminRouteRouteImport } from './../routes/admin/route'
import { Route as LoginRouteImport } from './../routes/login'
import { Route as StudentRouteRouteImport } from './../routes/student/route'
import { Route as TeacherRouteRouteImport } from './../routes/teacher/route'
import { Route as AdminIndexRouteImport } from './../routes/admin/index'
import { Route as AdminSettingsRouteImport } from './../routes/admin/settings'
import { Route as AdminUsersRouteImport } from './../routes/admin/users'
import { Route as StudentIndexRouteImport } from './../routes/student/index'
import { Route as StudentCoursesRouteImport } from './../routes/student/courses'
import { Route as TeacherIndexRouteImport } from './../routes/teacher/index'
import { Route as TeacherClassesRouteImport } from './../routes/teacher/classes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRouteRoute = StudentRouteRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRouteRoute = TeacherRouteRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentCoursesRoute = StudentCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => StudentRouteRoute,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherClassesRoute = TeacherClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => TeacherRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/student': typeof StudentRouteRouteWithChildren
  '/teacher': typeof TeacherRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/student/courses': typeof StudentCoursesRoute
  '/teacher/classes': typeof TeacherClassesRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/student/courses': typeof StudentCoursesRoute
  '/teacher/classes': typeof TeacherClassesRoute
  '/admin': typeof AdminIndexRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/student': typeof StudentRouteRouteWithChildren
  '/teacher': typeof TeacherRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/student/courses': typeof StudentCoursesRoute
  '/teacher/classes': typeof TeacherClassesRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/student'
    | '/teacher'
    | '/login'
    | '/admin/settings'
    | '/admin/users'
    | '/student/courses'
    | '/teacher/classes'
    | '/admin/'
    | '/student/'
    | '/teacher/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/settings'
    | '/admin/users'
    | '/student/courses'
    | '/teacher/classes'
    | '/admin'
    | '/student'
    | '/teacher'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/student'
    | '/teacher'
    | '/login'
    | '/admin/settings'
    | '/admin/users'
    | '/student/courses'
    | '/teacher/classes'
    | '/admin/'
    | '/student/'
    | '/teacher/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  StudentRouteRoute: typeof StudentRouteRouteWithChildren
  TeacherRouteRoute: typeof TeacherRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/courses': {
      id: '/student/courses'
      path: '/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof StudentCoursesRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/classes': {
      id: '/teacher/classes'
      path: '/classes'
      fullPath: '/teacher/classes'
      preLoaderRoute: typeof TeacherClassesRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface StudentRouteRouteChildren {
  StudentCoursesRoute: typeof StudentCoursesRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteRouteChildren: StudentRouteRouteChildren = {
  StudentCoursesRoute: StudentCoursesRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteRouteWithChildren = StudentRouteRoute._addFileChildren(
  StudentRouteRouteChildren,
)

interface TeacherRouteRouteChildren {
  TeacherClassesRoute: typeof TeacherClassesRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
}

const TeacherRouteRouteChildren: TeacherRouteRouteChildren = {
  TeacherClassesRoute: TeacherClassesRoute,
  TeacherIndexRoute: TeacherIndexRoute,
}

const TeacherRouteRouteWithChildren = TeacherRouteRoute._addFileChildren(
  TeacherRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  StudentRouteRoute: StudentRouteRouteWithChildren,
  TeacherRouteRoute: TeacherRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
