/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './../routes/__root'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as AdminRouteRouteImport } from './../routes/admin/route'
import { Route as StudentRouteRouteImport } from './../routes/student/route'
import { Route as TeacherRouteRouteImport } from './../routes/teacher/route'

const LoginLazyRouteImport = createFileRoute('/login')()
const AdminIndexLazyRouteImport = createFileRoute('/admin/')()
const AdminSettingsLazyRouteImport = createFileRoute('/admin/settings')()
const AdminUsersLazyRouteImport = createFileRoute('/admin/users')()
const StudentIndexLazyRouteImport = createFileRoute('/student/')()
const StudentCoursesLazyRouteImport = createFileRoute('/student/courses')()
const TeacherIndexLazyRouteImport = createFileRoute('/teacher/')()
const TeacherClassesLazyRouteImport = createFileRoute('/teacher/classes')()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./../routes/admin/route.lazy').then((d) => d.Route),
)
const LoginLazyRoute = LoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./../routes/login.lazy').then((d) => d.Route))
const StudentRouteRoute = StudentRouteRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./../routes/student/route.lazy').then((d) => d.Route),
)
const TeacherRouteRoute = TeacherRouteRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./../routes/teacher/route.lazy').then((d) => d.Route),
)
const AdminIndexLazyRoute = AdminIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any).lazy(() =>
  import('./../routes/admin/index.lazy').then((d) => d.Route),
)
const AdminSettingsLazyRoute = AdminSettingsLazyRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any).lazy(() =>
  import('./../routes/admin/settings.lazy').then((d) => d.Route),
)
const AdminUsersLazyRoute = AdminUsersLazyRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any).lazy(() =>
  import('./../routes/admin/users.lazy').then((d) => d.Route),
)
const StudentIndexLazyRoute = StudentIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRouteRoute,
} as any).lazy(() =>
  import('./../routes/student/index.lazy').then((d) => d.Route),
)
const StudentCoursesLazyRoute = StudentCoursesLazyRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => StudentRouteRoute,
} as any).lazy(() =>
  import('./../routes/student/courses.lazy').then((d) => d.Route),
)
const TeacherIndexLazyRoute = TeacherIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRouteRoute,
} as any).lazy(() =>
  import('./../routes/teacher/index.lazy').then((d) => d.Route),
)
const TeacherClassesLazyRoute = TeacherClassesLazyRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => TeacherRouteRoute,
} as any).lazy(() =>
  import('./../routes/teacher/classes.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/student': typeof StudentRouteRouteWithChildren
  '/teacher': typeof TeacherRouteRouteWithChildren
  '/login': typeof LoginLazyRoute
  '/admin/settings': typeof AdminSettingsLazyRoute
  '/admin/users': typeof AdminUsersLazyRoute
  '/student/courses': typeof StudentCoursesLazyRoute
  '/teacher/classes': typeof TeacherClassesLazyRoute
  '/admin/': typeof AdminIndexLazyRoute
  '/student/': typeof StudentIndexLazyRoute
  '/teacher/': typeof TeacherIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginLazyRoute
  '/admin/settings': typeof AdminSettingsLazyRoute
  '/admin/users': typeof AdminUsersLazyRoute
  '/student/courses': typeof StudentCoursesLazyRoute
  '/teacher/classes': typeof TeacherClassesLazyRoute
  '/admin': typeof AdminIndexLazyRoute
  '/student': typeof StudentIndexLazyRoute
  '/teacher': typeof TeacherIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/student': typeof StudentRouteRouteWithChildren
  '/teacher': typeof TeacherRouteRouteWithChildren
  '/login': typeof LoginLazyRoute
  '/admin/settings': typeof AdminSettingsLazyRoute
  '/admin/users': typeof AdminUsersLazyRoute
  '/student/courses': typeof StudentCoursesLazyRoute
  '/teacher/classes': typeof TeacherClassesLazyRoute
  '/admin/': typeof AdminIndexLazyRoute
  '/student/': typeof StudentIndexLazyRoute
  '/teacher/': typeof TeacherIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/student'
    | '/teacher'
    | '/login'
    | '/admin/settings'
    | '/admin/users'
    | '/student/courses'
    | '/teacher/classes'
    | '/admin/'
    | '/student/'
    | '/teacher/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/settings'
    | '/admin/users'
    | '/student/courses'
    | '/teacher/classes'
    | '/admin'
    | '/student'
    | '/teacher'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/student'
    | '/teacher'
    | '/login'
    | '/admin/settings'
    | '/admin/users'
    | '/student/courses'
    | '/teacher/classes'
    | '/admin/'
    | '/student/'
    | '/teacher/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  StudentRouteRoute: typeof StudentRouteRouteWithChildren
  TeacherRouteRoute: typeof TeacherRouteRouteWithChildren
  LoginLazyRoute: typeof LoginLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexLazyRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsLazyRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersLazyRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexLazyRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/courses': {
      id: '/student/courses'
      path: '/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof StudentCoursesLazyRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexLazyRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/classes': {
      id: '/teacher/classes'
      path: '/classes'
      fullPath: '/teacher/classes'
      preLoaderRoute: typeof TeacherClassesLazyRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminSettingsLazyRoute: typeof AdminSettingsLazyRoute
  AdminUsersLazyRoute: typeof AdminUsersLazyRoute
  AdminIndexLazyRoute: typeof AdminIndexLazyRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminSettingsLazyRoute: AdminSettingsLazyRoute,
  AdminUsersLazyRoute: AdminUsersLazyRoute,
  AdminIndexLazyRoute: AdminIndexLazyRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface StudentRouteRouteChildren {
  StudentCoursesLazyRoute: typeof StudentCoursesLazyRoute
  StudentIndexLazyRoute: typeof StudentIndexLazyRoute
}

const StudentRouteRouteChildren: StudentRouteRouteChildren = {
  StudentCoursesLazyRoute: StudentCoursesLazyRoute,
  StudentIndexLazyRoute: StudentIndexLazyRoute,
}

const StudentRouteRouteWithChildren = StudentRouteRoute._addFileChildren(
  StudentRouteRouteChildren,
)

interface TeacherRouteRouteChildren {
  TeacherClassesLazyRoute: typeof TeacherClassesLazyRoute
  TeacherIndexLazyRoute: typeof TeacherIndexLazyRoute
}

const TeacherRouteRouteChildren: TeacherRouteRouteChildren = {
  TeacherClassesLazyRoute: TeacherClassesLazyRoute,
  TeacherIndexLazyRoute: TeacherIndexLazyRoute,
}

const TeacherRouteRouteWithChildren = TeacherRouteRoute._addFileChildren(
  TeacherRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  StudentRouteRoute: StudentRouteRouteWithChildren,
  TeacherRouteRoute: TeacherRouteRouteWithChildren,
  LoginLazyRoute: LoginLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
